- name: Installing required packages. yum-utils, device-mapper-persistent-data, lvm2
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present


- name: Setting up the stable repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Installing the latest version of Docker Engine
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: " Starting and Enabling Docker service"
  service:
    name: docker
    state: started
