- name: Updating repositories cache and install packages
  apt:
    name:
      - wget
      - build-essential
      - unzip
      - openssl
      - libssl-dev apache2
      - php
      - libapache2-mod-php
      - php-gd
      - libgd-dev
    update_cache: yes
    state: present

- name: Add the user 'nagios' with a group of 'admin'
  user:
    name: nagios
    group: nagcmd